### PR TITLE
Inline elements support

### LINKED ISSUE #6: xliff 1.2 does not support inline elements like <g>, </x>, </bx>.
Supposedly for following Xliff 
```
<?xml version="1.0" encoding="UTF-8"?><xliff xmlns="urn:oasis:names:tc:xliff:document:1.2" xmlns:okp="okapi-framework:xliff-extensions" xmlns:its="http://www.w3.org/2005/11/its" xmlns:itsxlf="http://www.w3.org/ns/its-xliff/" its:version="2.0" version="1.2">
<file original="AppBody-Sample-English.docx" datatype="x-text/plain" source-language="en">
<body>
<trans-unit xml:space="preserve" id="3" resname="tu3-p2">
<source xml:lang="en">This is a sample text. The <g id="1">description</g> must disclose the invention in a manner sufficiently clear and complete for it to be carried out by a person skilled in the art.</source>
<target xml:lang="fr">This is a sample text. The <g id="1">description</g> must disclose the invention in a manner sufficiently clear and complete for it to be carried out by a person skilled in the art.</target>
</trans-unit>
</body>
</file>
</xliff>
```
the parsed source i get is

> This is a sample text. **The must disclose** the invention in a manner sufficiently clear and complete for it to be carried out by a person skilled in the art.

If you notice text is missing **description**.

Tested on xliff 1.2 only not on xliff 2.

### PR DESCRIPTION
**Pull request by probertson**
Adds support for inline elements in `source` and `target` values, as described in #13. (This also fixes #6)

Sorry it took me so long to get this wrapped up!

Assuming this is accepted, #13 can be closed since it was just meant as a strawman proposal for this work.

### CODE REVIEW

**Comment by adrai** [comment]
v4.0.0

**Comment by adrai** [comment]
@probertson small question: do you see a way to introduce a new option, i.e. `skipInline: true` which treats the source and target content always as string js <-> xliff ?

**Comment by probertson** [comment]
@adrai I'm not opposed to the idea if you have a use case for it. I'd have
to see some examples and look at the code to get an idea of what the work
would be.

**Comment by adrai** [comment]
need to think more about it...
like the angular cli xliff <-> json format

https://angular.io/cli/extract-i18n

**Comment by adrai** [comment]
Something like:
```xml
<?xml version="1.0" encoding="UTF-8" ?>
<xliff version="1.2" xmlns="urn:oasis:names:tc:xliff:document:1.2">
  <file source-language="en-US" datatype="plaintext" original="ng2.template">
    <body>
      <trans-unit id="27515543696334243" datatype="html">
        <source> Welcome (<x id="INTERPOLATION" equiv-text="{{ count }}"/>)&gt; <x id="ICU" equiv-text="{count, plural, =0 {noone} =1 {number one} other
    {anyone}}"/></source>
        <context-group purpose="location">
          <context context-type="sourcefile">src/app/app.component.html</context>
          <context context-type="linenumber">309,311</context>
        </context-group>
      </trans-unit>
      <trans-unit id="224564336508490125" datatype="html">
        <source>{VAR_PLURAL, plural, =0 {noone} =1 {number one} other {anyone}}</source>
        <context-group purpose="location">
          <context context-type="sourcefile">src/app/app.component.html</context>
          <context context-type="linenumber">310,311</context>
        </context-group>
      </trans-unit>
    </body>
  </file>
</xliff>
```

```json
{
  "locale": "en-US",
  "translations": {
    "8116496404797151711": " Welcome ({$INTERPOLATION}) {$ICU} ",
    "224564336508490125": "{VAR_PLURAL, plural, =0 {noone} =1 {number one} other {anyone}}",
    "702273782248450975": "{$INTERPOLATION} app is running!",
    "6485282072188277964": "{VAR_PLURAL, plural, 1= {Resource} , other {Resources}}",
    "4274046789977098738": "Here are some links to help you get started:"
  }
}
```

**Pull request merged**
