### PR TITLE
Add support for nested `<group>` tags

### LINKED ISSUE #28: xliff12ToJs ingnoring nested groups
## 🐛 Bug Report

`xliff12ToJs()` result will omit `group`s that are nested in other `group`. 

## To Reproduce

sandbox: https://codesandbox.io/s/heuristic-leavitt-vsumc?file=/src/index.js

## Expected behavior

`group`s inside of `group`s is valid structure according to spec: (http://docs.oasis-open.org/xliff/v1.2/cs02/xliff-core.html#group).
Therefore, I expect property inside of `group` that represents nested `group`s.

## Your Environment

- *module version*: >=5.0.6

### PR DESCRIPTION
**Pull request by probertson**
A `<group>` can contain translation units (1.2: `<trans-unit>`, 2.0: `<unit>`) and it can also contain other `<group>`s.

There was no support for `<group>` in the XLIFF 2.0 code so I added that as well.

This resolves #28

#### Checklist

- [x] only relevant code is changed (make a diff before you submit the PR)
- [x] run tests `npm run test`
- [x] tests are included
- [x] documentation is changed or added

### CODE REVIEW

**Comment by adrai** [comment]
Wouldn't it be better to enable this feature only with a flag?
I didn't check, but wouldn't converting a such a file => https://github.com/locize/xliff/pull/29/files#diff-b44d024de9f8f4635e08e69b29aefb6e to js, be breaking, because "group1" could be interpreted as a new key?

**Comment by adrai** [comment]
Probably targetOfjs and sourceOfjs needs to be checked too...

**Comment by probertson** [comment]
> I didn't check, but wouldn't converting a such a file => https://github.com/locize/xliff/pull/29/files#diff-b44d024de9f8f4635e08e69b29aefb6e to js, be breaking, because "group1" could be interpreted as a new key?

@adrai The tests pass, including the ones for those files. (I added the tests first and then added the code to make them work.) It distinguishes `<unit>` from `<group>`  (xml -> js) by checking the name of the tag, and (js -> xml) by checking whether the object (translation unit or group) has a `groupChildren` property.

Maybe I'm misunderstanding your question though. And it's very possible that I'm missing something. I initially thought this would require a breaking change to the JS object structure, but I just reused the structure that was already in use for groups and it seemed to work.

**Comment by adrai** [comment]
ok, will merge asap

**Comment by probertson** [comment]
Oh, I meant to tag @amadare42 on this to double check that this matches what you expect

**Comment by adrai** [comment]
released with v5.1.0

**Pull request merged**
