### PR TITLE
Use function, not arrow function, to stay compatible with older node …

### PR DESCRIPTION
**Pull request by digitalica**
I tried to run on a Ubuntu 14.04 machine, and it worked only after these changes.

```
$ node -v
v0.12.17

### CODE REVIEW

**Comment by adrai** [comment]
0.12 is end of life...
Can't you update node?

**Comment by digitalica** [comment]
I should upgrade my OS, and node will go with it ;-) but not today...  For now this changes seemed to be faster / easier / less risky.

But I agree supporting old versions is not most important, but on the other hand: I don't see any reason not to.

May i suggest a version check / error otherwise?

**Comment by adrai** [comment]
is this ok? https://github.com/locize/xliff/commit/6d4f348a0f806a98aa8f20261f2abc7a1ab76c0e

**Comment by digitalica** [comment]
haha..  works for me i guess ;-)

**Pull request closed without merging**
