### PR TITLE
Mrk support

### PR DESCRIPTION
**Pull request by k4zh**
Hi,

Thank you for your xliff library I'm using to read & write v1.2 xliff files.

I've got an issue because the mrk xml element is not handled and I need it to mark string parts as "not translatable".

http://docs.oasis-open.org/xliff/v1.2/os/xliff-core.html#mrk

Here is a branch I suggest you to consider to add this support.

Thank you to let me now your feedback about this commit.

Thanks
Regards

k4zh

#### Checklist

- [ Y, but a little part of dead code removed ] only relevant code is changed (make a diff before you submit the PR)
- [ Y ] run tests `npm run test`
- [ Y ] tests are included
- [ N ] documentation is changed or added

### CODE REVIEW

**Comment by adrai** [comment]
@probertson What do you think?

**Comment by adrai** [comment]
@k4zh @probertson Do you think it makes sense to create a special handling for: `<mrk mtype="seg">` (**mtype** => **seg**) ?
Example:
```xml
      <trans-unit id="key3">
        <source>What if?</source>
        <target><mrk mtype="seg" mid="1">Wat moet?</mrk></target>
      </trans-unit>
```
would be converted to:
```json
      {
        "key3": {
          "source": "What if?",
          "target": "Wat moet?"
        }
      }
```

**Comment by k4zh** [comment]
Hi @adrai,

Thank you for your review.

I don't think that such a special handling is required since it would **change data** instead to **convert data format**: why the xliff segment identifier would have to be censured in the produced json?

With the suggested branch, the result of this input is:

```json
"key3": {
  "source": "What if?",
  "target": {
    "Marker": {
      "contents": "Wat moet?",
      "mid": "1",
      "mtype": "seg",
    }
  }
```

Moreover, what would be the special handling for the following input?

```xml
</trans-unit><trans-unit id="key3">
    <source>What if?</source>
    <target>
        <mrk mtype="seg" mid="1">Brand: 
            <mrk mtype="protected">ABrandName</mrk>
        </mrk>
    </target>
</trans-unit>
```

With the suggested branch, it is handled this way:

```json"key3": {
  "source": "What if?"
  "target": {
    "Marker": {
      "contents": [
        "Brand: "
        {
          "Marker": {
            "contents": "ABrandName"
            "mtype": "protected"
          }
        }
      ]
      "mid": "1"
      "mtype": "seg"
    }
  }
}
```

**Comment by adrai** [comment]
thx, included in v5.3.0

**Comment by k4zh** [comment]
Thanks!

**Pull request merged**
